baseURL = "/"
languageCode = "en-us"
title = "Super Duper Evil Co."
themesDir = "themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.svg"
    alt = "Super Duper Evil Co."

  [params.homepage_meta_tags]
    meta_description = "Super Duper Evil Co. is a data visualization consultancy that helps companies understand what the hell is going on."
    meta_og_title = "Super Duper Evil Co."
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Super Duper Evil Co. is a data visualization consultancy that helps companies understand what the hell is going on."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ulfaslak"
    meta_twitter_creator = "@ulfaslak"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
